spring:
  application:
    name: demo

END_POINT_URL:
  BANK_LIST_FOR_SWIFT: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BANK_LIST_FOR_NCF: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  PRODUCT_LIST: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
